"""is_delete flag for repo

Revision ID: 73c8a1bb6460
Revises: d8e8c7358b2b
Create Date: 2026-08-30 13:03:34.067646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c8a1bb6460'
down_revision: Union[str, Sequence[str], None] = 'd8e8c7358b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'is_deleted')
    # ### end Alembic commands ###
