"""migration message

Revision ID: d8e8c7358b2b
Revises: b7d9c2f4a8e1
Create Date: 2026-08-28 21:39:25.795440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e8c7358b2b'
down_revision: Union[str, Sequence[str], None] = 'b7d9c2f4a8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_repositories_repo_id'), 'repositories', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_repo_id'), table_name='repositories')
    op.drop_column('repositories', 'is_private')
    # ### end Alembic commands ###
